// Autogenerated from Pigeon (v24.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package dev.flutterberlin.flutter_gemma

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

enum class PreferredBackend(val raw: Int) {
  UNKNOWN(0),
  CPU(1),
  GPU(2),
  GPU_FLOAT16(3),
  GPU_MIXED(4),
  GPU_FULL(5),
  TPU(6);

  companion object {
    fun ofRaw(raw: Int): PreferredBackend? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class PermissionType(val raw: Int) {
  CONTACTS(0),
  CALENDAR(1),
  NOTIFICATIONS(2),
  PHOTOS(3),
  CALL_LOG(4),
  FILES(5);

  companion object {
    fun ofRaw(raw: Int): PermissionType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class PermissionStatus(val raw: Int) {
  GRANTED(0),
  DENIED(1),
  RESTRICTED(2),
  NOT_DETERMINED(3);

  companion object {
    fun ofRaw(raw: Int): PermissionStatus? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Document types supported for extraction */
enum class DocumentType(val raw: Int) {
  PLAIN_TEXT(0),
  MARKDOWN(1),
  PDF(2),
  RTF(3),
  HTML(4),
  OTHER(5);

  companion object {
    fun ofRaw(raw: Int): DocumentType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class CallType(val raw: Int) {
  INCOMING(0),
  OUTGOING(1),
  MISSED(2),
  REJECTED(3),
  BLOCKED(4),
  VOICEMAIL(5),
  UNKNOWN(6);

  companion object {
    fun ofRaw(raw: Int): CallType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class RetrievalResult (
  val id: String,
  val content: String,
  val similarity: Double,
  val metadata: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RetrievalResult {
      val id = pigeonVar_list[0] as String
      val content = pigeonVar_list[1] as String
      val similarity = pigeonVar_list[2] as Double
      val metadata = pigeonVar_list[3] as String?
      return RetrievalResult(id, content, similarity, metadata)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      content,
      similarity,
      metadata,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class VectorStoreStats (
  val documentCount: Long,
  val vectorDimension: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): VectorStoreStats {
      val documentCount = pigeonVar_list[0] as Long
      val vectorDimension = pigeonVar_list[1] as Long
      return VectorStoreStats(documentCount, vectorDimension)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      documentCount,
      vectorDimension,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class EntityResult (
  val id: String,
  val name: String,
  val type: String,
  val description: String? = null,
  val metadata: String? = null,
  val lastModified: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): EntityResult {
      val id = pigeonVar_list[0] as String
      val name = pigeonVar_list[1] as String
      val type = pigeonVar_list[2] as String
      val description = pigeonVar_list[3] as String?
      val metadata = pigeonVar_list[4] as String?
      val lastModified = pigeonVar_list[5] as Long
      return EntityResult(id, name, type, description, metadata, lastModified)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      name,
      type,
      description,
      metadata,
      lastModified,
    )
  }
}

/**
 * Entity result with embedding included (for similarity calculations)
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class EntityWithEmbedding (
  val id: String,
  val name: String,
  val type: String,
  val description: String? = null,
  val metadata: String? = null,
  val lastModified: Long,
  val embedding: List<Double>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): EntityWithEmbedding {
      val id = pigeonVar_list[0] as String
      val name = pigeonVar_list[1] as String
      val type = pigeonVar_list[2] as String
      val description = pigeonVar_list[3] as String?
      val metadata = pigeonVar_list[4] as String?
      val lastModified = pigeonVar_list[5] as Long
      val embedding = pigeonVar_list[6] as List<Double>
      return EntityWithEmbedding(id, name, type, description, metadata, lastModified, embedding)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      name,
      type,
      description,
      metadata,
      lastModified,
      embedding,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class RelationshipResult (
  val id: String,
  val sourceId: String,
  val targetId: String,
  val type: String,
  val weight: Double,
  val metadata: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RelationshipResult {
      val id = pigeonVar_list[0] as String
      val sourceId = pigeonVar_list[1] as String
      val targetId = pigeonVar_list[2] as String
      val type = pigeonVar_list[3] as String
      val weight = pigeonVar_list[4] as Double
      val metadata = pigeonVar_list[5] as String?
      return RelationshipResult(id, sourceId, targetId, type, weight, metadata)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      sourceId,
      targetId,
      type,
      weight,
      metadata,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CommunityResult (
  val id: String,
  val level: Long,
  val summary: String,
  val entityIds: List<String?>,
  val metadata: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CommunityResult {
      val id = pigeonVar_list[0] as String
      val level = pigeonVar_list[1] as Long
      val summary = pigeonVar_list[2] as String
      val entityIds = pigeonVar_list[3] as List<String?>
      val metadata = pigeonVar_list[4] as String?
      return CommunityResult(id, level, summary, entityIds, metadata)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      level,
      summary,
      entityIds,
      metadata,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class GraphStats (
  val entityCount: Long,
  val relationshipCount: Long,
  val communityCount: Long,
  val maxCommunityLevel: Long,
  val vectorDimension: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): GraphStats {
      val entityCount = pigeonVar_list[0] as Long
      val relationshipCount = pigeonVar_list[1] as Long
      val communityCount = pigeonVar_list[2] as Long
      val maxCommunityLevel = pigeonVar_list[3] as Long
      val vectorDimension = pigeonVar_list[4] as Long
      return GraphStats(entityCount, relationshipCount, communityCount, maxCommunityLevel, vectorDimension)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      entityCount,
      relationshipCount,
      communityCount,
      maxCommunityLevel,
      vectorDimension,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ContactResult (
  val id: String,
  val givenName: String? = null,
  val familyName: String? = null,
  val organizationName: String? = null,
  val jobTitle: String? = null,
  val emailAddresses: List<String?>,
  val phoneNumbers: List<String?>,
  val lastModified: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ContactResult {
      val id = pigeonVar_list[0] as String
      val givenName = pigeonVar_list[1] as String?
      val familyName = pigeonVar_list[2] as String?
      val organizationName = pigeonVar_list[3] as String?
      val jobTitle = pigeonVar_list[4] as String?
      val emailAddresses = pigeonVar_list[5] as List<String?>
      val phoneNumbers = pigeonVar_list[6] as List<String?>
      val lastModified = pigeonVar_list[7] as Long
      return ContactResult(id, givenName, familyName, organizationName, jobTitle, emailAddresses, phoneNumbers, lastModified)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      givenName,
      familyName,
      organizationName,
      jobTitle,
      emailAddresses,
      phoneNumbers,
      lastModified,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CalendarEventResult (
  val id: String,
  val title: String,
  val location: String? = null,
  val notes: String? = null,
  val startDate: Long,
  val endDate: Long,
  val attendees: List<String?>,
  val lastModified: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CalendarEventResult {
      val id = pigeonVar_list[0] as String
      val title = pigeonVar_list[1] as String
      val location = pigeonVar_list[2] as String?
      val notes = pigeonVar_list[3] as String?
      val startDate = pigeonVar_list[4] as Long
      val endDate = pigeonVar_list[5] as Long
      val attendees = pigeonVar_list[6] as List<String?>
      val lastModified = pigeonVar_list[7] as Long
      return CalendarEventResult(id, title, location, notes, startDate, endDate, attendees, lastModified)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      title,
      location,
      notes,
      startDate,
      endDate,
      attendees,
      lastModified,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class GraphQueryResult (
  val entities: List<EntityResult?>,
  val relationships: List<RelationshipResult?>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): GraphQueryResult {
      val entities = pigeonVar_list[0] as List<EntityResult?>
      val relationships = pigeonVar_list[1] as List<RelationshipResult?>
      return GraphQueryResult(entities, relationships)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      entities,
      relationships,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class EntityWithScoreResult (
  val entity: EntityResult,
  val score: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): EntityWithScoreResult {
      val entity = pigeonVar_list[0] as EntityResult
      val score = pigeonVar_list[1] as Double
      return EntityWithScoreResult(entity, score)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      entity,
      score,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CommunityWithScoreResult (
  val community: CommunityResult,
  val score: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CommunityWithScoreResult {
      val community = pigeonVar_list[0] as CommunityResult
      val score = pigeonVar_list[1] as Double
      return CommunityWithScoreResult(community, score)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      community,
      score,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PhotoResult (
  val id: String,
  val filename: String? = null,
  val width: Long,
  val height: Long,
  val creationDate: Long,
  val modificationDate: Long,
  val latitude: Double? = null,
  val longitude: Double? = null,
  val locationName: String? = null,
  val duration: Long? = null,
  val mediaType: String,
  val mimeType: String? = null,
  val fileSize: Long? = null,
  val thumbnailBytes: ByteArray? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PhotoResult {
      val id = pigeonVar_list[0] as String
      val filename = pigeonVar_list[1] as String?
      val width = pigeonVar_list[2] as Long
      val height = pigeonVar_list[3] as Long
      val creationDate = pigeonVar_list[4] as Long
      val modificationDate = pigeonVar_list[5] as Long
      val latitude = pigeonVar_list[6] as Double?
      val longitude = pigeonVar_list[7] as Double?
      val locationName = pigeonVar_list[8] as String?
      val duration = pigeonVar_list[9] as Long?
      val mediaType = pigeonVar_list[10] as String
      val mimeType = pigeonVar_list[11] as String?
      val fileSize = pigeonVar_list[12] as Long?
      val thumbnailBytes = pigeonVar_list[13] as ByteArray?
      return PhotoResult(id, filename, width, height, creationDate, modificationDate, latitude, longitude, locationName, duration, mediaType, mimeType, fileSize, thumbnailBytes)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      filename,
      width,
      height,
      creationDate,
      modificationDate,
      latitude,
      longitude,
      locationName,
      duration,
      mediaType,
      mimeType,
      fileSize,
      thumbnailBytes,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class DocumentResult (
  val id: String,
  val name: String,
  val path: String,
  val documentType: DocumentType,
  val mimeType: String? = null,
  val fileSize: Long,
  val createdDate: Long,
  val modifiedDate: Long,
  val textPreview: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DocumentResult {
      val id = pigeonVar_list[0] as String
      val name = pigeonVar_list[1] as String
      val path = pigeonVar_list[2] as String
      val documentType = pigeonVar_list[3] as DocumentType
      val mimeType = pigeonVar_list[4] as String?
      val fileSize = pigeonVar_list[5] as Long
      val createdDate = pigeonVar_list[6] as Long
      val modifiedDate = pigeonVar_list[7] as Long
      val textPreview = pigeonVar_list[8] as String?
      return DocumentResult(id, name, path, documentType, mimeType, fileSize, createdDate, modifiedDate, textPreview)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      name,
      path,
      documentType,
      mimeType,
      fileSize,
      createdDate,
      modifiedDate,
      textPreview,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CallLogResult (
  val id: String,
  val name: String? = null,
  val phoneNumber: String,
  val callType: CallType,
  val timestamp: Long,
  val duration: Long,
  val isRead: Boolean,
  val geocodedLocation: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CallLogResult {
      val id = pigeonVar_list[0] as String
      val name = pigeonVar_list[1] as String?
      val phoneNumber = pigeonVar_list[2] as String
      val callType = pigeonVar_list[3] as CallType
      val timestamp = pigeonVar_list[4] as Long
      val duration = pigeonVar_list[5] as Long
      val isRead = pigeonVar_list[6] as Boolean
      val geocodedLocation = pigeonVar_list[7] as String?
      return CallLogResult(id, name, phoneNumber, callType, timestamp, duration, isRead, geocodedLocation)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      name,
      phoneNumber,
      callType,
      timestamp,
      duration,
      isRead,
      geocodedLocation,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class DetectedFace (
  val x: Double,
  val y: Double,
  val width: Double,
  val height: Double,
  val confidence: Double,
  val recognizedPerson: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DetectedFace {
      val x = pigeonVar_list[0] as Double
      val y = pigeonVar_list[1] as Double
      val width = pigeonVar_list[2] as Double
      val height = pigeonVar_list[3] as Double
      val confidence = pigeonVar_list[4] as Double
      val recognizedPerson = pigeonVar_list[5] as String?
      return DetectedFace(x, y, width, height, confidence, recognizedPerson)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      x,
      y,
      width,
      height,
      confidence,
      recognizedPerson,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class DetectedObject (
  val label: String,
  val confidence: Double,
  val x: Double,
  val y: Double,
  val width: Double,
  val height: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DetectedObject {
      val label = pigeonVar_list[0] as String
      val confidence = pigeonVar_list[1] as Double
      val x = pigeonVar_list[2] as Double
      val y = pigeonVar_list[3] as Double
      val width = pigeonVar_list[4] as Double
      val height = pigeonVar_list[5] as Double
      return DetectedObject(label, confidence, x, y, width, height)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      label,
      confidence,
      x,
      y,
      width,
      height,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class DetectedText (
  val text: String,
  val confidence: Double,
  val x: Double,
  val y: Double,
  val width: Double,
  val height: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DetectedText {
      val text = pigeonVar_list[0] as String
      val confidence = pigeonVar_list[1] as Double
      val x = pigeonVar_list[2] as Double
      val y = pigeonVar_list[3] as Double
      val width = pigeonVar_list[4] as Double
      val height = pigeonVar_list[5] as Double
      return DetectedText(text, confidence, x, y, width, height)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      text,
      confidence,
      x,
      y,
      width,
      height,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PhotoAnalysisResult (
  val photoId: String,
  val faces: List<DetectedFace?>,
  val objects: List<DetectedObject?>,
  val texts: List<DetectedText?>,
  val labels: List<String?>,
  val dominantColors: String? = null,
  val isScreenshot: Boolean,
  val hasText: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PhotoAnalysisResult {
      val photoId = pigeonVar_list[0] as String
      val faces = pigeonVar_list[1] as List<DetectedFace?>
      val objects = pigeonVar_list[2] as List<DetectedObject?>
      val texts = pigeonVar_list[3] as List<DetectedText?>
      val labels = pigeonVar_list[4] as List<String?>
      val dominantColors = pigeonVar_list[5] as String?
      val isScreenshot = pigeonVar_list[6] as Boolean
      val hasText = pigeonVar_list[7] as Boolean
      return PhotoAnalysisResult(photoId, faces, objects, texts, labels, dominantColors, isScreenshot, hasText)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      photoId,
      faces,
      objects,
      texts,
      labels,
      dominantColors,
      isScreenshot,
      hasText,
    )
  }
}
private open class PigeonInterfacePigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PreferredBackend.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PermissionType.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PermissionStatus.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          DocumentType.ofRaw(it.toInt())
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          CallType.ofRaw(it.toInt())
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RetrievalResult.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          VectorStoreStats.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          EntityResult.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          EntityWithEmbedding.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RelationshipResult.fromList(it)
        }
      }
      139.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CommunityResult.fromList(it)
        }
      }
      140.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          GraphStats.fromList(it)
        }
      }
      141.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ContactResult.fromList(it)
        }
      }
      142.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CalendarEventResult.fromList(it)
        }
      }
      143.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          GraphQueryResult.fromList(it)
        }
      }
      144.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          EntityWithScoreResult.fromList(it)
        }
      }
      145.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CommunityWithScoreResult.fromList(it)
        }
      }
      146.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PhotoResult.fromList(it)
        }
      }
      147.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DocumentResult.fromList(it)
        }
      }
      148.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CallLogResult.fromList(it)
        }
      }
      149.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DetectedFace.fromList(it)
        }
      }
      150.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DetectedObject.fromList(it)
        }
      }
      151.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DetectedText.fromList(it)
        }
      }
      152.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PhotoAnalysisResult.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is PreferredBackend -> {
        stream.write(129)
        writeValue(stream, value.raw)
      }
      is PermissionType -> {
        stream.write(130)
        writeValue(stream, value.raw)
      }
      is PermissionStatus -> {
        stream.write(131)
        writeValue(stream, value.raw)
      }
      is DocumentType -> {
        stream.write(132)
        writeValue(stream, value.raw)
      }
      is CallType -> {
        stream.write(133)
        writeValue(stream, value.raw)
      }
      is RetrievalResult -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is VectorStoreStats -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is EntityResult -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is EntityWithEmbedding -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is RelationshipResult -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      is CommunityResult -> {
        stream.write(139)
        writeValue(stream, value.toList())
      }
      is GraphStats -> {
        stream.write(140)
        writeValue(stream, value.toList())
      }
      is ContactResult -> {
        stream.write(141)
        writeValue(stream, value.toList())
      }
      is CalendarEventResult -> {
        stream.write(142)
        writeValue(stream, value.toList())
      }
      is GraphQueryResult -> {
        stream.write(143)
        writeValue(stream, value.toList())
      }
      is EntityWithScoreResult -> {
        stream.write(144)
        writeValue(stream, value.toList())
      }
      is CommunityWithScoreResult -> {
        stream.write(145)
        writeValue(stream, value.toList())
      }
      is PhotoResult -> {
        stream.write(146)
        writeValue(stream, value.toList())
      }
      is DocumentResult -> {
        stream.write(147)
        writeValue(stream, value.toList())
      }
      is CallLogResult -> {
        stream.write(148)
        writeValue(stream, value.toList())
      }
      is DetectedFace -> {
        stream.write(149)
        writeValue(stream, value.toList())
      }
      is DetectedObject -> {
        stream.write(150)
        writeValue(stream, value.toList())
      }
      is DetectedText -> {
        stream.write(151)
        writeValue(stream, value.toList())
      }
      is PhotoAnalysisResult -> {
        stream.write(152)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface PlatformService {
  fun createModel(maxTokens: Long, modelPath: String, loraRanks: List<Long>?, preferredBackend: PreferredBackend?, maxNumImages: Long?, callback: (Result<Unit>) -> Unit)
  fun closeModel(callback: (Result<Unit>) -> Unit)
  fun createSession(temperature: Double, randomSeed: Long, topK: Long, topP: Double?, loraPath: String?, enableVisionModality: Boolean?, callback: (Result<Unit>) -> Unit)
  fun closeSession(callback: (Result<Unit>) -> Unit)
  fun sizeInTokens(prompt: String, callback: (Result<Long>) -> Unit)
  fun addQueryChunk(prompt: String, callback: (Result<Unit>) -> Unit)
  fun addImage(imageBytes: ByteArray, callback: (Result<Unit>) -> Unit)
  fun generateResponse(callback: (Result<String>) -> Unit)
  fun generateResponseAsync(callback: (Result<Unit>) -> Unit)
  fun stopGeneration(callback: (Result<Unit>) -> Unit)
  fun createEmbeddingModel(modelPath: String, tokenizerPath: String, preferredBackend: PreferredBackend?, callback: (Result<Unit>) -> Unit)
  fun closeEmbeddingModel(callback: (Result<Unit>) -> Unit)
  fun generateEmbeddingFromModel(text: String, callback: (Result<List<Double>>) -> Unit)
  fun generateEmbeddingsFromModel(texts: List<String>, callback: (Result<List<Any?>>) -> Unit)
  fun getEmbeddingDimension(callback: (Result<Long>) -> Unit)
  fun initializeVectorStore(databasePath: String, callback: (Result<Unit>) -> Unit)
  fun addDocument(id: String, content: String, embedding: List<Double>, metadata: String?, callback: (Result<Unit>) -> Unit)
  fun searchSimilar(queryEmbedding: List<Double>, topK: Long, threshold: Double, callback: (Result<List<RetrievalResult>>) -> Unit)
  fun getVectorStoreStats(callback: (Result<VectorStoreStats>) -> Unit)
  fun clearVectorStore(callback: (Result<Unit>) -> Unit)
  fun closeVectorStore(callback: (Result<Unit>) -> Unit)
  fun initializeGraphStore(databasePath: String, callback: (Result<Unit>) -> Unit)
  fun addEntity(id: String, name: String, type: String, embedding: List<Double>, description: String?, metadata: String?, lastModified: Long, callback: (Result<Unit>) -> Unit)
  fun updateEntity(id: String, name: String?, type: String?, embedding: List<Double>?, description: String?, metadata: String?, lastModified: Long?, callback: (Result<Unit>) -> Unit)
  fun deleteEntity(id: String, callback: (Result<Unit>) -> Unit)
  fun getEntity(id: String, callback: (Result<EntityResult?>) -> Unit)
  fun getEntitiesByType(type: String, callback: (Result<List<EntityResult>>) -> Unit)
  fun getEntitiesWithEmbeddingsByType(type: String, callback: (Result<List<EntityWithEmbedding>>) -> Unit)
  fun addRelationship(id: String, sourceId: String, targetId: String, type: String, weight: Double, metadata: String?, callback: (Result<Unit>) -> Unit)
  fun deleteRelationship(id: String, callback: (Result<Unit>) -> Unit)
  fun getRelationships(entityId: String, callback: (Result<List<RelationshipResult>>) -> Unit)
  fun addCommunity(id: String, level: Long, summary: String, entityIds: List<String>, embedding: List<Double>, metadata: String?, callback: (Result<Unit>) -> Unit)
  fun updateCommunitySummary(id: String, summary: String, embedding: List<Double>, callback: (Result<Unit>) -> Unit)
  fun getCommunitiesByLevel(level: Long, callback: (Result<List<CommunityResult>>) -> Unit)
  fun getEntityNeighbors(entityId: String, depth: Long, relationshipType: String?, callback: (Result<List<EntityResult>>) -> Unit)
  fun searchEntitiesBySimilarity(queryEmbedding: List<Double>, topK: Long, threshold: Double, entityType: String?, callback: (Result<List<EntityWithScoreResult>>) -> Unit)
  fun searchCommunitiesBySimilarity(queryEmbedding: List<Double>, topK: Long, level: Long?, callback: (Result<List<CommunityWithScoreResult>>) -> Unit)
  fun executeGraphQuery(query: String, callback: (Result<GraphQueryResult>) -> Unit)
  fun getGraphStats(callback: (Result<GraphStats>) -> Unit)
  fun clearGraphStore(callback: (Result<Unit>) -> Unit)
  fun closeGraphStore(callback: (Result<Unit>) -> Unit)
  fun checkPermission(type: PermissionType, callback: (Result<PermissionStatus>) -> Unit)
  fun requestPermission(type: PermissionType, callback: (Result<PermissionStatus>) -> Unit)
  fun fetchContacts(sinceTimestamp: Long?, limit: Long?, callback: (Result<List<ContactResult>>) -> Unit)
  fun fetchCalendarEvents(sinceTimestamp: Long?, startDate: Long?, endDate: Long?, limit: Long?, callback: (Result<List<CalendarEventResult>>) -> Unit)
  fun fetchPhotos(sinceTimestamp: Long?, limit: Long?, includeLocation: Boolean?, callback: (Result<List<PhotoResult>>) -> Unit)
  fun fetchCallLog(sinceTimestamp: Long?, limit: Long?, callback: (Result<List<CallLogResult>>) -> Unit)
  /**
   * Opens a document picker for the user to select files.
   * Returns a list of documents the user selected.
   */
  fun pickDocuments(allowedExtensions: List<String>?, allowMultiple: Boolean?, callback: (Result<List<DocumentResult>>) -> Unit)
  fun fetchDocuments(sinceTimestamp: Long?, limit: Long?, allowedExtensions: List<String>?, callback: (Result<List<DocumentResult>>) -> Unit)
  fun readDocumentContent(documentId: String, maxLength: Long?, callback: (Result<String?>) -> Unit)
  fun getPhotoThumbnail(photoId: String, maxWidth: Long?, maxHeight: Long?, callback: (Result<ByteArray?>) -> Unit)
  fun analyzePhoto(photoId: String, imageBytes: ByteArray, detectFaces: Boolean?, detectObjects: Boolean?, detectText: Boolean?, callback: (Result<PhotoAnalysisResult>) -> Unit)
  fun startIndexingForegroundService(callback: (Result<Unit>) -> Unit)
  fun stopIndexingForegroundService(callback: (Result<Unit>) -> Unit)
  fun updateIndexingProgress(progress: Double, phase: String, entities: Long, relationships: Long, callback: (Result<Unit>) -> Unit)
  fun isIndexingServiceRunning(callback: (Result<Boolean>) -> Unit)

  companion object {
    /** The codec used by PlatformService. */
    val codec: MessageCodec<Any?> by lazy {
      PigeonInterfacePigeonCodec()
    }
    /** Sets up an instance of `PlatformService` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: PlatformService?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_gemma.PlatformService.createModel$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val maxTokensArg = args[0] as Long
            val modelPathArg = args[1] as String
            val loraRanksArg = args[2] as List<Long>?
            val preferredBackendArg = args[3] as PreferredBackend?
            val maxNumImagesArg = args[4] as Long?
            api.createModel(maxTokensArg, modelPathArg, loraRanksArg, preferredBackendArg, maxNumImagesArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_gemma.PlatformService.closeModel$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.closeModel{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_gemma.PlatformService.createSession$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val temperatureArg = args[0] as Double
            val randomSeedArg = args[1] as Long
            val topKArg = args[2] as Long
            val topPArg = args[3] as Double?
            val loraPathArg = args[4] as String?
            val enableVisionModalityArg = args[5] as Boolean?
            api.createSession(temperatureArg, randomSeedArg, topKArg, topPArg, loraPathArg, enableVisionModalityArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_gemma.PlatformService.closeSession$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.closeSession{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_gemma.PlatformService.sizeInTokens$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val promptArg = args[0] as String
            api.sizeInTokens(promptArg) { result: Result<Long> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_gemma.PlatformService.addQueryChunk$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val promptArg = args[0] as String
            api.addQueryChunk(promptArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_gemma.PlatformService.addImage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val imageBytesArg = args[0] as ByteArray
            api.addImage(imageBytesArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_gemma.PlatformService.generateResponse$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.generateResponse{ result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_gemma.PlatformService.generateResponseAsync$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.generateResponseAsync{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_gemma.PlatformService.stopGeneration$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.stopGeneration{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_gemma.PlatformService.createEmbeddingModel$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val modelPathArg = args[0] as String
            val tokenizerPathArg = args[1] as String
            val preferredBackendArg = args[2] as PreferredBackend?
            api.createEmbeddingModel(modelPathArg, tokenizerPathArg, preferredBackendArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_gemma.PlatformService.closeEmbeddingModel$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.closeEmbeddingModel{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_gemma.PlatformService.generateEmbeddingFromModel$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val textArg = args[0] as String
            api.generateEmbeddingFromModel(textArg) { result: Result<List<Double>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_gemma.PlatformService.generateEmbeddingsFromModel$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val textsArg = args[0] as List<String>
            api.generateEmbeddingsFromModel(textsArg) { result: Result<List<Any?>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_gemma.PlatformService.getEmbeddingDimension$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getEmbeddingDimension{ result: Result<Long> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_gemma.PlatformService.initializeVectorStore$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val databasePathArg = args[0] as String
            api.initializeVectorStore(databasePathArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_gemma.PlatformService.addDocument$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idArg = args[0] as String
            val contentArg = args[1] as String
            val embeddingArg = args[2] as List<Double>
            val metadataArg = args[3] as String?
            api.addDocument(idArg, contentArg, embeddingArg, metadataArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_gemma.PlatformService.searchSimilar$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val queryEmbeddingArg = args[0] as List<Double>
            val topKArg = args[1] as Long
            val thresholdArg = args[2] as Double
            api.searchSimilar(queryEmbeddingArg, topKArg, thresholdArg) { result: Result<List<RetrievalResult>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_gemma.PlatformService.getVectorStoreStats$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getVectorStoreStats{ result: Result<VectorStoreStats> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_gemma.PlatformService.clearVectorStore$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.clearVectorStore{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_gemma.PlatformService.closeVectorStore$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.closeVectorStore{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_gemma.PlatformService.initializeGraphStore$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val databasePathArg = args[0] as String
            api.initializeGraphStore(databasePathArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_gemma.PlatformService.addEntity$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idArg = args[0] as String
            val nameArg = args[1] as String
            val typeArg = args[2] as String
            val embeddingArg = args[3] as List<Double>
            val descriptionArg = args[4] as String?
            val metadataArg = args[5] as String?
            val lastModifiedArg = args[6] as Long
            api.addEntity(idArg, nameArg, typeArg, embeddingArg, descriptionArg, metadataArg, lastModifiedArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_gemma.PlatformService.updateEntity$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idArg = args[0] as String
            val nameArg = args[1] as String?
            val typeArg = args[2] as String?
            val embeddingArg = args[3] as List<Double>?
            val descriptionArg = args[4] as String?
            val metadataArg = args[5] as String?
            val lastModifiedArg = args[6] as Long?
            api.updateEntity(idArg, nameArg, typeArg, embeddingArg, descriptionArg, metadataArg, lastModifiedArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_gemma.PlatformService.deleteEntity$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idArg = args[0] as String
            api.deleteEntity(idArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_gemma.PlatformService.getEntity$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idArg = args[0] as String
            api.getEntity(idArg) { result: Result<EntityResult?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_gemma.PlatformService.getEntitiesByType$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val typeArg = args[0] as String
            api.getEntitiesByType(typeArg) { result: Result<List<EntityResult>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_gemma.PlatformService.getEntitiesWithEmbeddingsByType$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val typeArg = args[0] as String
            api.getEntitiesWithEmbeddingsByType(typeArg) { result: Result<List<EntityWithEmbedding>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_gemma.PlatformService.addRelationship$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idArg = args[0] as String
            val sourceIdArg = args[1] as String
            val targetIdArg = args[2] as String
            val typeArg = args[3] as String
            val weightArg = args[4] as Double
            val metadataArg = args[5] as String?
            api.addRelationship(idArg, sourceIdArg, targetIdArg, typeArg, weightArg, metadataArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_gemma.PlatformService.deleteRelationship$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idArg = args[0] as String
            api.deleteRelationship(idArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_gemma.PlatformService.getRelationships$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val entityIdArg = args[0] as String
            api.getRelationships(entityIdArg) { result: Result<List<RelationshipResult>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_gemma.PlatformService.addCommunity$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idArg = args[0] as String
            val levelArg = args[1] as Long
            val summaryArg = args[2] as String
            val entityIdsArg = args[3] as List<String>
            val embeddingArg = args[4] as List<Double>
            val metadataArg = args[5] as String?
            api.addCommunity(idArg, levelArg, summaryArg, entityIdsArg, embeddingArg, metadataArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_gemma.PlatformService.updateCommunitySummary$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idArg = args[0] as String
            val summaryArg = args[1] as String
            val embeddingArg = args[2] as List<Double>
            api.updateCommunitySummary(idArg, summaryArg, embeddingArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_gemma.PlatformService.getCommunitiesByLevel$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val levelArg = args[0] as Long
            api.getCommunitiesByLevel(levelArg) { result: Result<List<CommunityResult>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_gemma.PlatformService.getEntityNeighbors$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val entityIdArg = args[0] as String
            val depthArg = args[1] as Long
            val relationshipTypeArg = args[2] as String?
            api.getEntityNeighbors(entityIdArg, depthArg, relationshipTypeArg) { result: Result<List<EntityResult>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_gemma.PlatformService.searchEntitiesBySimilarity$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val queryEmbeddingArg = args[0] as List<Double>
            val topKArg = args[1] as Long
            val thresholdArg = args[2] as Double
            val entityTypeArg = args[3] as String?
            api.searchEntitiesBySimilarity(queryEmbeddingArg, topKArg, thresholdArg, entityTypeArg) { result: Result<List<EntityWithScoreResult>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_gemma.PlatformService.searchCommunitiesBySimilarity$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val queryEmbeddingArg = args[0] as List<Double>
            val topKArg = args[1] as Long
            val levelArg = args[2] as Long?
            api.searchCommunitiesBySimilarity(queryEmbeddingArg, topKArg, levelArg) { result: Result<List<CommunityWithScoreResult>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_gemma.PlatformService.executeGraphQuery$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val queryArg = args[0] as String
            api.executeGraphQuery(queryArg) { result: Result<GraphQueryResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_gemma.PlatformService.getGraphStats$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getGraphStats{ result: Result<GraphStats> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_gemma.PlatformService.clearGraphStore$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.clearGraphStore{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_gemma.PlatformService.closeGraphStore$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.closeGraphStore{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_gemma.PlatformService.checkPermission$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val typeArg = args[0] as PermissionType
            api.checkPermission(typeArg) { result: Result<PermissionStatus> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_gemma.PlatformService.requestPermission$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val typeArg = args[0] as PermissionType
            api.requestPermission(typeArg) { result: Result<PermissionStatus> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_gemma.PlatformService.fetchContacts$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sinceTimestampArg = args[0] as Long?
            val limitArg = args[1] as Long?
            api.fetchContacts(sinceTimestampArg, limitArg) { result: Result<List<ContactResult>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_gemma.PlatformService.fetchCalendarEvents$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sinceTimestampArg = args[0] as Long?
            val startDateArg = args[1] as Long?
            val endDateArg = args[2] as Long?
            val limitArg = args[3] as Long?
            api.fetchCalendarEvents(sinceTimestampArg, startDateArg, endDateArg, limitArg) { result: Result<List<CalendarEventResult>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_gemma.PlatformService.fetchPhotos$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sinceTimestampArg = args[0] as Long?
            val limitArg = args[1] as Long?
            val includeLocationArg = args[2] as Boolean?
            api.fetchPhotos(sinceTimestampArg, limitArg, includeLocationArg) { result: Result<List<PhotoResult>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_gemma.PlatformService.fetchCallLog$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sinceTimestampArg = args[0] as Long?
            val limitArg = args[1] as Long?
            api.fetchCallLog(sinceTimestampArg, limitArg) { result: Result<List<CallLogResult>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_gemma.PlatformService.pickDocuments$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val allowedExtensionsArg = args[0] as List<String>?
            val allowMultipleArg = args[1] as Boolean?
            api.pickDocuments(allowedExtensionsArg, allowMultipleArg) { result: Result<List<DocumentResult>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_gemma.PlatformService.fetchDocuments$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sinceTimestampArg = args[0] as Long?
            val limitArg = args[1] as Long?
            val allowedExtensionsArg = args[2] as List<String>?
            api.fetchDocuments(sinceTimestampArg, limitArg, allowedExtensionsArg) { result: Result<List<DocumentResult>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_gemma.PlatformService.readDocumentContent$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val documentIdArg = args[0] as String
            val maxLengthArg = args[1] as Long?
            api.readDocumentContent(documentIdArg, maxLengthArg) { result: Result<String?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_gemma.PlatformService.getPhotoThumbnail$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val photoIdArg = args[0] as String
            val maxWidthArg = args[1] as Long?
            val maxHeightArg = args[2] as Long?
            api.getPhotoThumbnail(photoIdArg, maxWidthArg, maxHeightArg) { result: Result<ByteArray?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_gemma.PlatformService.analyzePhoto$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val photoIdArg = args[0] as String
            val imageBytesArg = args[1] as ByteArray
            val detectFacesArg = args[2] as Boolean?
            val detectObjectsArg = args[3] as Boolean?
            val detectTextArg = args[4] as Boolean?
            api.analyzePhoto(photoIdArg, imageBytesArg, detectFacesArg, detectObjectsArg, detectTextArg) { result: Result<PhotoAnalysisResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_gemma.PlatformService.startIndexingForegroundService$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.startIndexingForegroundService{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_gemma.PlatformService.stopIndexingForegroundService$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.stopIndexingForegroundService{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_gemma.PlatformService.updateIndexingProgress$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val progressArg = args[0] as Double
            val phaseArg = args[1] as String
            val entitiesArg = args[2] as Long
            val relationshipsArg = args[3] as Long
            api.updateIndexingProgress(progressArg, phaseArg, entitiesArg, relationshipsArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_gemma.PlatformService.isIndexingServiceRunning$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.isIndexingServiceRunning{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
